import React from "react";

function BlogIntro() {
  return (
    <div>
      <p className="max-w-[75ch]">
        {/* The Internet used to be a place for humans to interact with other
        humans. With the exciting innovations in algoritmes that can make people
        believe the world is ran by lizards, this is no longer the case. Each
        day I wonder if what I'm reading was created by a real person or
        generated by AI trying to sell me something, and ironically, you're
        probably wondering the same about this very blogpost. */}
      </p>
      <p className="max-w-[75ch] pt-5">
        {/* How can we return to genuine human connection without the interference
        of smart algorithms? While most people rely on conventional chat apps
        like WhatsApp or Discord, I wanted to create something unique. Like most
        great innovations in life, the idea behind Toaster came from my attempt
        to create a singular gift I could give to everyone on Christmas. In this
        blogpost I will explain my journy creating Toaster */}
      </p>
    </div>
  );
}

export default BlogIntro;
